apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: devopsinaction
  labels:
    name: voting-service
    app: voting-app
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
     name: votingpod
     app: voting-app
