apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: devopsinaction
  labels:
    name: redis-service
    app: voting-app
spec:
  ports:
  - port: 6379
    name: redisport
    targetPort: 6379
  type: ClusterIP
  selector:
     name: redis-pod
     app: voting-app
