apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdep
  namespace: devopsinaction
  labels:
    name: postgresdep
    app: voting-app
spec:
  replicas: 3
  template:
    metadata:
      name: dbpod
      labels:
        name: dbpod
        app: voting-app
    spec:
      containers:
      - name: postgres
        image: yogeshraheja/thinknyxdb:v1
        ports:
        - containerPort: 5432
  selector:
    matchLabels:
      app: voting-app
      name: dbpod
