apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: devopsinaction
  namespace: devopsinaction
  labels:
    name: db-service
    app: voting-app
spec:
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
  selector:
     name: postgres-pod
     app: voting-app
